name = "PlutoMapPicker"
uuid = "474136ad-924f-47fa-9297-876420b5dc85"
authors = ["Luka van der Plas"]
version = "0.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
